# Generated by Django 5.0.6 on 2024-05-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergySystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity_mw", models.FloatField()),
                ("efficiency", models.FloatField()),
                ("cost_per_mw", models.FloatField()),
            ],
        ),
    ]
